### ISSUE TITLE
SchemaError on preparePayment()

### ISSUE THREAD

**Issue by cscchat** [casinocoin/casinocoin-libjs#1]
So, after setting up the tutorial quickstart, I was trying to prepare a payment, just to test things, and I got a schema error.  In order to make sure it wasn't my code I came over to the libjs  repo and grabbed the sample code to run.

````
Connected...
{ SchemaError: no such schema </tag>
    at Validator.resolve (/Users/deft/Code/my_casinocoin_experiment/node_modules/jsonschema/lib/validator.js:258:11)
    at Validator.validateSchema (/Users/deft/Code/my_casinocoin_experiment/node_modules/jsonschema/lib/validator.js:185:25)
    at Validator.validateProperties (/Users/deft/Code/my_casinocoin_experiment/node_modules/jsonschema/lib/attribute.js:199:20)
    at Validator.validateSchema (/Users/deft/Code/my_casinocoin_experiment/node_modules/jsonschema/lib/validator.js:197:34)
    at Validator.validateSchema (/Users/deft/Code/my_casinocoin_experiment/node_modules/jsonschema/lib/validator.js:187:17)
    at Validator.testSchemaNoThrow (/Users/deft/Code/my_casinocoin_experiment/node_modules/jsonschema/lib/attribute.js:64:18)
    at Array.filter (<anonymous>)
    at Validator.validateOneOf (/Users/deft/Code/my_casinocoin_experiment/node_modules/jsonschema/lib/attribute.js:161:28)
    at Validator.validateSchema (/Users/deft/Code/my_casinocoin_experiment/node_modules/jsonschema/lib/validator.js:197:34)
    at Validator.validateSchema (/Users/deft/Code/my_casinocoin_experiment/node_modules/jsonschema/lib/validator.js:187:17) message: 'no such schema </tag>', schema: { '$ref': 'tag' } }
```

the messed up part is that their is [a tag schema file](https://github.com/casinocoin/casinocoin-libjs/blob/master/src/common/schemas/objects/tag.json) which i tracked down.  so I am kind of stumped.

Could it be that 'tag' is a keyword that is being interpolated from 'tag' -> </tag> by jsonschema?

**Comment by cscchat** [comment]
Found a [similar issue on Ripple](https://github.com/ripple/ripple-lib/issues/880).  has to do with using json schema 1.2.3 or 1.2.4.

Need to revert to 1.2.2.  testing now
